on: ["issue_comment"]

jobs:
  check_basic_valid:
    name: Check Issue Comment Sha  
    runs-on: ubuntu-latest
    steps:
      - name: Show Issue Comment
        run: echo "${{ github.event.comment.body }}"
      - uses: actions/setup-python@v1
        with:
          python-version: "^3.5.0" # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: "x64"
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Check Contains raa+
        id: contain_ra
        run: |
          touch error.txt
          python ci/issue.py check "${{ github.event.comment.body }}" error.txt
          echo ::set-output name=msg::$(cat error.txt)
      - name: Checkout gh-pages
        if: steps.contain_ra.outputs.msg == ''
        run: |
          mkdir gh-pages
          cd gh-pages
          git clone --branch gh-pages https://github.com/${GITHUB_REPOSITORY} .
      - name: More Check
        if: steps.contain_ra.outputs.msg == ''
        run: |
          cd gh-pages
          python ../ci/issue.py exists $(cat ../target_sha.txt) ../error.txt
          cd ..
          mkdir rust-analyzer
          cd rust-analyzer
          git clone https://github.com/rust-analyzer/rust-analyzer.git .
          python ../ci/issue.py valid $(cat ../target_sha.txt) ../error.txt
      - name: Read Error
        id: more_check
        run: |
          echo ::set-output name=msg::$(cat error.txt)
      - name: Tell failure story
        if: steps.more_check.outputs.msg != 'NO_MSG' && steps.more_check.outputs.msg != ''
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: '👀 {{steps.read_result.outputs.msg}}'})
      - name: Send Deployment
        if: steps.more_check.outputs.msg == ''
        run: |
          chmod a+rx ./ci/send_deployment.sh
          ./ci/send_deployment.sh
      - uses: actions/github-script@0.3.0
        if: steps.more_check.outputs.msg == ''
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: '🤖 Your request is queued, Thanks!'})


          
