on:
  push:
    branches:
      - master

jobs:
  build_ra:
    runs-on: ubuntu-latest
    name: Build RA anal
    steps:
      - name: Checkout RA
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/rust-analyzer/rust-analyzer.git .

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src
      - name: Cargo target cache
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p ra_cli
      - uses: actions/upload-artifact@v1
        with:
          name: ra_cil
          path: ./target/release/ra_cli
      - name: Prepare build directory for cache
        run: |
          find ./target/debug -maxdepth 1 -type f -delete && \
          rm -fr ./target/debug/{deps,.fingerprint}/{*ra_*,*heavy_test*,*gen_lsp*,*thread_worker*} && \
          rm -f  ./target/.rustc_info.json
