on:
  push:
    branches:
      - master

jobs:
  build_ra:
    runs-on: ubuntu-latest
    name: Build RA
    steps:
      - name: Checkout RA
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/rust-analyzer/rust-analyzer.git .

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src
      - name: Cargo target cache
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Generate artifact
        id: artifcat
        run: |
          mkdir ra_cli
          cp ./target/release/ra_cli ./ra_cli/ra_cli
          echo $(git rev-parse --short HEAD) > ./ra_cli/commit
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p ra_cli
      - uses: actions/upload-artifact@v1
        with:
          name: ra_cli
          path: ./target/release/ra_cli
  run_ra:
    name: Run ra_cli
    runs-on: ubuntu-latest
    needs: build_ra
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src
      - uses: actions/checkout@v1
        with:
          submodules: true
          ref: refs/heads/master
      - uses: actions/download-artifact@v1
        with:
          name: ra_cli
      - name: Run analysis-stats
        run: |
          ./ci/run_stats.sh
      - name: Prepare gh-pages
          mkdir gh-pages          
          cd gh-pages
          git clone https://github.com/${GITHUB_REPOSITORY} .
          cp ../ra-stats-output.txt "./ra-stats-output-$(cat ../ra_cli/commit).txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages
