on: 
  push:
    branches:
      - master

jobs:
  build_ra:
    runs-on: ubuntu-latest
    name: Build RA anal
    steps:
    - name: Checkout RA      
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/rust-analyzer/rust-analyzer.git .
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -p ra_cli
    - uses: actions/upload-artifact@v1
      with:
        name: ra_cil
        path: $GITHUB_WORKSPACE/build/release/ra_cli


